app/models/__init__.py
__author__ = 'adriel'

app/models/truck_model.py
import random

class Food_Truck:
    """
    Representation of a truck document.
    """
    type_name = "truck"

    def __init__(self):
        self._id = self.generate_id()
        self.name = None
        self.latitude = None
        self.longitude = None
        self.schedule = None
        self.approved = False

    def generate_id(self):
        ID_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
        num = random.getrandbits(122)
        encoding = ''
        for x in xrange(21):
            num, rem = divmod(num, 62)
            encoding += ID_ALPHABET[rem]
        return '{}_{}'.format(self.type_name, encoding)

app/__init__.py
from flask import Flask

app = Flask(__name__)
app.config.from_object('config')

from app import routes

from routes import uber

app.register_blueprint(uber)

app/routes.py
from flask import Blueprint, render_template, request

from app.views import main
from app.views import foodtrucks

uber = Blueprint('uber', __name__, url_prefix='/uber',
                    template_folder='templates', static_folder='static')


@uber.errorhandler(404)
def page_not_found(e):
    return render_template('index.html')

@uber.route("/")
def main_application():
    return main.google_maps()

@uber.route("/open", methods=["GET"])
def food_trucks_open():
    return foodtrucks.open()

app/views/foodtrucks.py
from datetime import datetime

from flask import request, jsonify
from pytz import timezone

from connections import get_truck_db

def open():
    day_array = ("Mo", "Tu", "We", "Th", "Fr", "Sa", "Su")
    time = request.args.get('time')
    day = day_array[datetime.now(tz=timezone('US/Pacific')).weekday()]
    db = get_truck_db()
    trucks = db.view('distance/approved', startkey=[day, time], endkey=[day, time, {}])
    results = []
    for truck in trucks:
        results.append(tuple(truck.value))
    return jsonify({"results": results})

app/views/main.py
from datetime import datetime

from flask import render_template
from pytz import timezone

import connections
from ingestion import time_in_sequence

def google_maps():
    pacific_time = datetime.now(tz=timezone('US/Pacific')).time()
    str_pacific_time = pacific_time.strftime("%H:%M:%S")
    current_time = time_in_sequence(str_pacific_time, str_pacific_time)
    API_KEY = connections.gmaps_api()
    return render_template('index.html',
                           API_KEY=API_KEY,
                           TIMING=current_time)

app/templates/index.html
{% extends "maps_layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all">
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" media="all">
<link href="{{ url_for('static', filename='css/bootstrap-theme.css') }}" rel="stylesheet" type="text/css" media="all">
<link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet" type="text/css" media="all">
<script src="{{ url_for('static', filename='js/jquery-1.11.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% endblock %}

{% block upper_body %}
    <label class="radio-inline">
        <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="morning" {% if TIMING['morning']%}checked=""{% endif %}> Morning (6am - 11am)
    </label>
    <label class="radio-inline">
        <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="afternoon" {% if TIMING['afternoon']%}checked=""{% endif %}> Afternoon (11am - 4pm)
    </label>
    <label class="radio-inline">
        <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="evening" {% if TIMING['evening']%}checked=""{% endif %}> Evening (4pm - 11pm)
    </label>
    <label class="radio-inline">
        <input type="radio" name="inlineRadioOptions" id="inlineRadio4" value="late_night" {% if TIMING['late_night']%}checked=""{% endif %}> Late Night
    </label>
{% endblock %}

{% block script %}


{% endblock %}

app/templates/maps_layout.html
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}</style>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ API_KEY }}"></script>
        {% block head %}{% endblock %}
    </head>
    <body>
        {% block upper_body %}{% endblock %}
        <div id="map-canvas"></div>
        {% block lower_body %}{% endblock %}
    </body>
    <script type="text/javascript">
    var gmarkers = [];
    var main_marker = [];
    var marker = false;
    var map = false;

        function load_map(latlng) {
            console.log(latlng)
            var mapOptions = {
                center: latlng,
                zoom: 15
            };

            if (map === false) {
                map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);
            };

            if (main_marker.length == 0) {
                 marker = new google.maps.Marker({
                    position: latlng,
                    draggable:true,
                    animation: google.maps.Animation.DROP,
                    map: map
                });
                main_marker.push(marker)

            };
            console.log(marker.position)
            var selectedVal = "";
            var selected = $("input[type='radio'][name='inlineRadioOptions']:checked");
            if (selected.length > 0) {
                selectedVal = selected.val();
            }

            $.ajax({
                url: "{{ url_for('uber.food_trucks_open') }}",
                type: 'get',
                dataType: 'json',
                data: {
                    time: selectedVal
                },
                success: function(data) {
                    $.each(data, function (key, val) {
                        if (key == "results") {
                            $.each(val, function (i, item) {
                                newLatLng = new google.maps.LatLng(parseFloat(item[1]), parseFloat(item[2]));
                                var iconBase = "{{ url_for('static', filename='images/truck.png') }}";
                                var truckmarker = new google.maps.Marker({
                                    position: newLatLng,
                                    map: map,
                                    animation: google.maps.Animation.DROP,
                                    title: item[0],
                                    icon: iconBase,
                                    url: "https://www.google.com/maps/dir/" + item[1] + "," + item[2] + "/" + latlng['k'] + "," + latlng['B']
                                });
                                gmarkers.push(truckmarker)
                                var infowindow = new google.maps.InfoWindow({
                                    content: truckmarker.title
                                });
                                google.maps.event.addListener(truckmarker, 'mouseover', (function () {
                                    infowindow.open(map, truckmarker);
                                }));
                                google.maps.event.addListener(truckmarker, 'mouseout', function() {
                                    infowindow.close();
                                });
                                google.maps.event.addListener(truckmarker, 'click', function() {
                                    window.location.href = this.url;
                                });
                            })
                        }
                    })
                }
            });
        };

        function initialize() {
            if (navigator.geolocation){
                navigator.geolocation.getCurrentPosition(function(position) {
                    var latitude, longitude, myLatlng;
                    latitude = position.coords.latitude;
                    longitude = position.coords.longitude;

                    myLatlng = new google.maps.LatLng(latitude,longitude);

                    load_map(myLatlng)
                    }, showError
                )
            }
        };

        function showError(error) {
            var latitude, longitude, myLatlng;
            switch(error.code) {
                case error.PERMISSION_DENIED:
                    latitude = 37.7744649;
                    longitude = -122.4184558;
                    myLatlng = new google.maps.LatLng(latitude,longitude);

                    load_map(myLatlng)
                    break;

                case error.POSITION_UNAVAILABLE:
                    latitude = 37.7744649;
                    longitude = -122.4184558;
                    myLatlng = new google.maps.LatLng(latitude,longitude);

                    load_map(myLatlng)
                    break;

                case error.TIMEOUT:
                    latitude = 37.7744649;
                    longitude = -122.4184558;
                    myLatlng = new google.maps.LatLng(latitude,longitude);

                    load_map(myLatlng)
                    break;

                case error.UNKNOWN_ERROR:
                    latitude = 37.7744649;
                    longitude = -122.4184558;
                    myLatlng = new google.maps.LatLng(latitude,longitude);

                    load_map(myLatlng)
                    break;

            }
        }
        google.maps.event.addDomListener(window, 'load', initialize);
        $("input[name=inlineRadioOptions]:radio").change(function () {
            for(i=0; i<gmarkers.length; i++){
                gmarkers[i].setMap(null);
            }
            gmarkers = []
            var time = $("input[name=inlineRadioOptions]:checked").val();
            if (navigator.geolocation){
                navigator.geolocation.getCurrentPosition(function(position) {
                    var latitude, longitude, myLatlng;
                    latitude = position.coords.latitude;
                    longitude = position.coords.longitude;

                    myLatlng = new google.maps.LatLng(latitude,longitude);

                    load_map(myLatlng)
                }, showError)
            }
        });
        {% block script %}{% endblock %}

    </script>
</html>